name: Lint

on:
  push:
    branches:
      - main
      - master
      - develop

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          accept-android-sdk-licenses: true

      - name: Install SDK
        run: |
          yes | sdkmanager --licenses >/dev/null || true

          sdkmanager \
            "platform-tools" \
            "platforms;android-36" \
            "build-tools;36.0.0"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run Android Lint
        run: |
          ./gradlew \
            --no-daemon \
            --stacktrace \
            lint
